### ISSUE TITLE
Unable to run workflow tests

### ISSUE THREAD

**Issue by mtekman** [usegalaxy-eu/workflow-testing#30]
I am unable to run the `run_galaxy_workflow_tests.sh` script properly.

It seems I am missing some dependencies to get this running properly, but I cannot work out what.

Error message:

```
./run_galaxy_workflow_tests.sh 
+ :
++ date +%s
+ nonce=1543075641
+ history_name=' 1543075641'
+ export GALAXY_USER_KEY=<hidden>
+ GALAXY_USER_KEY=<hidden>
+ set +e
+ planemo test --history_name ' 1543075641' --galaxy_url '' --galaxy_user_key <hidden> --no_shed_install --engine external_galaxy ''
Usage: planemo test [OPTIONS] TOOL_PATH
Try "planemo test --help" for help.

Error: Invalid value for "TOOL_PATH": Path "" is not readable.
+ planemo_exit_code=2
+ set -e
+ ((  planemo_exit_code > 0  ))
++ parsec histories get_histories --name ' 1543075641'
++ jq -r '.[0].id'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/parsec/decorators.py", line 13, in custom_exception
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/parsec/decorators.py", line 31, in list_output
    output = wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/parsec/commands/histories/get_histories.py", line 33, in cli
    return ctx.gi.histories.get_histories(history_id=history_id, name=name, deleted=deleted)
AttributeError: 'Context' object has no attribute 'gi'

'Context' object has no attribute 'gi'
+ history_id=
++ parsec histories update_history --importable
++ jq -r .username_and_slug
Usage: parsec histories update_history [OPTIONS] HISTORY_ID
Try "parsec histories update_history -h" for help.

Error: Missing argument "HISTORY_ID".
+ history_slug=
+ echo '<html><head></head><body style="margin:0;padding:0;"><iframe style="border:none;width:100%;height:100%;" src="https://usegalaxy.eu/"></iframe></body></html>'
+ exit 2
```

I have the following pip packages installed, both globally, and also within a conda environment where I also tried to run the script.

```
galaxy-parsec     1.0.5
bioblend          0.11.0
planemo           0.58.0.dev0
```

As far as I know, I have no other parsec package.

I am experiencing this problem both on Ubuntu and Arch.

**Comment by bgruening** [comment]
Added an introduction to the readme in https://github.com/usegalaxy-eu/workflow-testing/commit/2e9a5c78a270e55d3e445051fdb1107e1440ae69

**Comment by erasche** [comment]
> --galaxy_url ''

your GALAXY_URL env var is empty.
